import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
root = tk.Tk()
root.title("GUI Development in Python - Tkinter")
root.geometry("900x700")
root.iconbitmap("hello.ico")
def on_button_click():
    messagebox.showinfo("Event Triggered", "Button Clicked")
def exit_app():
    root.quit()
menu_bar = tk.Menu(root)
file_menu = tk.Menu(menu_bar, tearoff=0)
file_menu.add_command(label="Exit", command=exit_app)
menu_bar.add_cascade(label="File", menu=file_menu)
help_menu = tk.Menu(menu_bar, tearoff=0)
help_menu.add_command(
    label = "About",
    command = lambda: messagebox.showinfo("About", "Tkinter")
)
menu_bar.add_cascade(label="Help", menu=help_menu)
root.config(menu=menu_bar)
toolbar = tk.Frame(root, bg='light grey', relief=tk.RAISED, bd=2)
btn_toolbar = tk.Button(toolbar, text="Click Me", command=on_button_click)
btn_toolbar.pack(side=tk.LEFT, padx=2)
toolbar.pack(side=tk.TOP, fill=tk.X)
status_var = tk.StringVar()
status_var.set("Ready")
status_bar = tk.Label(root, textvariable=status_var, bd=1, relief=tk.SUNKEN, anchor=tk.W)
status_bar.pack(side=tk.BOTTOM, fill=tk.X)
main_frame = tk.Frame(root)
main_frame.pack(pady=10)
label = tk.Label(main_frame, text="Enter your Name:")
label.grid(row=0, column=0, padx=5, pady=5)
scale = tk.Scale(root, from_=0, to=100, orient=tk.HORIZONTAL, label = "Volume")
scale.pack(pady=10)
spinbox = tk.Spinbox(root, from_=1, to=10)
spinbox.pack(pady=10)
listbox = tk.Listbox(root, height=4)
listbox.insert(1, "Python")
listbox.insert(2, "Java")
listbox.insert(3, "C++")
listbox.pack(pady=10)
combo = ttk.Combobox(root, values=["India", "USA", "UK", " "])
combo.set("select country")
combo.pack(pady=10)
columns = ("ID", "Name", "Course")
tree = ttk.Treeview(root, columns=columns, show="headings")
tree.heading("ID", text="ID")
tree.heading("Name", text="Name")
tree.heading("Course", text="Course")
tree.insert("", tk.END, values=(1,"Rama", "Python"))
tree.insert("", tk.END, values=(2,"Teja", "Java"))
tree.pack(pady=10)
canvas = tk.Canvas(root, width=300, height=200, bg="white")
canvas.create_line(10, 10, 200, 10, fill="blue", width=2)
canvas.create_rectangle(50, 50, 150, 120, outline="red", width=2)
canvas.pack(pady=10)
root.mainloop()